name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@master
    - name: Install Dependencies
      run: npm ci
    - name: Run Test
      run: npm test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate Bin File
        run: npx bin-file-gen -y
      - name: Copy Package.json To dist
        run:  cp package.json ./dist
      - name: Publish NPM
        run: cd ./dist && npm publish --tag master && cd ../
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
# npm version `npm view . version`-`git rev-parse --verify --short HEAD`
